<?php include_once(__DIR__."//../site/mysql.php"); ?>
<?php include_once(__DIR__."//../site/secur.php"); ?>

<?php if($_GET['type'] == "sab"){?>
<html>
<head>
<title>Управление Michome. Управление сабвуфером</title>
<link rel="stylesheet" type="text/css" href="styles/style.css"/>
<script type="text/javascript" src="/site/MicrofLibrary.js"></script>  

<script>	
function SensToIR(q){
	var host = '<?echo $_SERVER['HTTP_HOST'];?>';
	
    postAjax('http://<?echo $_SERVER['HTTP_HOST'];?>/michome/api/setcmd.php?device='+ '192.168.1.34' +'&cmd='+ 'ir?code='+q, "POST", "", function(){});
}
</script>
</head>
<body>
		<div class = "body_alfa"></div>
		<div class = "body">
			<div class = "title_menu">Управление Michome. Комнаты. Управление сабвуфером</div>
			<div style="text-align: left;" class = "com">
                <div style="width: auto; height: auto; text-align: left;" class = "components">
					<div class = "components_alfa">
						<div style="width: 100%" class = "components_text">
                            <div>
                            <!-- Image Map Generated by http://www.image-map.net/ -->
                                <img style="border-radius: 15px; -moz-user-select: none; -webkit-user-select: none; -ms-user-select: none; user-select: none;" style="pointer-events: none;" src="/site/rc58.jpg" usemap="#image-map">
                                <map name="image-map">
                                    <area target="_blank" alt="Включить" title="Включить" OnClick="SensToIR('1119703215')" coords="68,99,27" shape="circle">
                                    <area target="_blank" alt="Вход" title="Вход" OnClick="SensToIR('1119684855')" coords="314,98,23" shape="circle">
                                    <area target="_blank" alt="Режим" title="Режим" OnClick="SensToIR('1119701175')" coords="316,182,24" shape="circle">
                                    <area target="_blank" alt="Громче" title="Громче" OnClick="SensToIR('1119739935')" coords="316,263,23" shape="circle">
                                    <area target="_blank" alt="Тише" title="Тише" OnClick="SensToIR('1119709335')" coords="316,344,23" shape="circle">
                                    <area target="_blank" alt="Сброс" title="Сброс" OnClick="SensToIR('1119682815')" coords="68,426,25" shape="circle">
                                    <area target="_blank" alt="Выключить звук" title="Выключить звук" OnClick="SensToIR('1119707295')" coords="69,180,22" shape="circle">
                                    <area target="_blank" alt="Бас увеличить" title="Бас увеличить" OnClick="SensToIR('1119719535')" coords="151,99,27" shape="circle">
                                    <area target="_blank" alt="Бас уменьшить" title="Бас уменьшить" OnClick="SensToIR('1119735855')" coords="151,179,25" shape="circle">
                                    <area target="_blank" alt="Треб увеличить" title="Треб увеличить" OnClick="SensToIR('1119717495')" coords="232,97,25" shape="circle">
                                    <area target="_blank" alt="Треб уменишить" title="Треб уменишить" OnClick="SensToIR('1119733815')" coords="234,180,24" shape="circle">
                                    <area target="_blank" alt="Задние увеличить" title="Задние увеличить" OnClick="SensToIR('1119699135')" coords="69,263,25" shape="circle">
                                    <area target="_blank" alt="Задние уменьшить" title="Задние уменьшить" OnClick="SensToIR('1119690975')" coords="68,346,26" shape="circle">
                                    <area target="_blank" alt="Центр увеличить" title="Центр увеличить" OnClick="SensToIR('1119731775')" coords="150,261,26" shape="circle">
                                    <area target="_blank" alt="Центр уменьшить" title="Центр уменьшить" OnClick="SensToIR('1119723615')" coords="151,344,25" shape="circle">
                                    <area target="_blank" alt="Саб увеличить" title="Саб увеличить" OnClick="SensToIR('1119727695')" coords="232,262,26" shape="circle">
                                    <area target="_blank" alt="Саб уменьшить" title="Саб уменьшить"OnClick="SensToIR('1119686895')"  coords="233,345,25" shape="circle">
                                </map>
                            </div>
                        </div>
					</div>
				</div>               
			</div>
		</div>
        
		<?php require_once("/var/www/html/site/verhn.php");?>        
	</body>

</html>
<?php } ?>
